# details see http://muyunyun.cn/create-react-doc/默认主题

# Site
# title:

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
menu: Introduction
## set init open menu keys
# menuOpenKeys:

# site theme
theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
# user:
# repo:

# Available values: en | zh-cn
language: en